### ISSUE TITLE
FEATURE REQUEST: Rich Text

### ISSUE THREAD

**Issue by mwagdi** [hey-car/heycar-uikit#31]
### Description

Component that renders content from rich text fields with the proper styling.
![Screenshot 2022-06-01 at 10 26 51](https://user-images.githubusercontent.com/16118089/171361503-f7c1f911-0649-4979-bfb5-f2de4631b821.png)

### Benefit / Value

Currently it's implemented in the [intl-seo-hub](library). If this will be re-used outside the domain of `intl-seo-hub` it would make sense to extract this to the global design system

### Proposal

Creating a solution that could convert HTML tags (`p`, `a`, `ul`...) to use the typography component

**Comment by derek-heycar** [comment]
@mwagdi I'm not sure about this proposal. 
This component has a specific domain it processes the RicheText from headless CMS, it is not sound like the Global design system component.
From my perspective, this component should be on the SEO library side, and this component should use our Typography component inside for the correctly displayed texts.
