### ISSUE TITLE
FEATURE REQUEST: Logo

### ISSUE THREAD

**Issue by MahmoudAli-heycar** [hey-car/heycar-uikit#59]
## Feature Request

Since we have a default value for `fontSize` prop of 65px, maybe it's better to make passing the `fontSize` prop **optional**.

**Comment by derek-heycar** [comment]
@MahmoudAli-heycar Hey. thanks for the request, rest assured, we will fix it in the nearest time, as soon as possible.

@hcafaq ^^^

**Comment by hcafaq** [comment]
I've created a PR for this: https://github.com/hey-car/heycar-uikit/pull/61
