### ISSUE TITLE
FEATURE REQUEST: Right icon in Badge

### ISSUE THREAD

**Issue by vperera-heycar** [hey-car/heycar-uikit#67]
## Feature Request

In es-web-app we use badges for special campaigns like this: 

![image](https://user-images.githubusercontent.com/87384947/187202473-3f715ef4-152d-43eb-8530-edee8a151a63.png)

Would be possible to have a "rightIcon" property, like the "leftIcon" for this case? or should we handle this special case directly on es-web-app (e.g. including the icon as part of the badge text)?

### Description

Describe the feature

### Benefit / Value

Describe what problem this feature aims to solve or what benefits can come out from this feature

### Proposal

New property "rightIcon" rendered at the end of the badge text

### Alternative solutions

State other solutions you might propose

### Acceptance criteria

- State requirements of solution
- in bullet point format

**Comment by derek-heycar** [comment]
@vperera-heycar 
Hey, thanks for the request. 

Of course, it is possible, but all availability by the API we getting from the [design templates](https://www.figma.com/file/rrvkvQEoVTOHa7MzyKSaoz/OTP-Global-Design-System?node-id=4031%3A102387). 
That means the designer team decides about certain possibilities for the particular component. You can request these changes or make a discussion about them in the HeyCat Slack Channel #global-design-system-design-review
