### ISSUE TITLE
BUG: Button doesn't accept secondary as a color prop value.

### ISSUE THREAD

**Issue by MahmoudAli-heycar** [hey-car/heycar-uikit#81]
I'm trying to pass `secondary` value to Button's `color` prop but it fails in TS compilation resulting in this error
```
Type secondary is not assignable to type primary | tertiary | undefined 
```
I checked the dist code in `button.d.ts` file, the `secondary` value is not defined after building, only supports 
```
color?: "primary" | "tertiary";
```

**Comment by esraltintas** [comment]
Hi @MahmoudAli-heycar we do not have “Secondary colour (teal)” button, only primary and tertiary, and we will have whatsapp color option

**Comment by MahmoudAli-heycar** [comment]
Thanks @esraltintas, closing the issue.
